title   Arch Linux (systemd-boot)
linux   /EFI/Arch/vmlinuz-linux
initrd  /EFI/Arch/intel-ucode.img
initrd  /EFI/Arch/initramfs-linux.img
options root=UUID=7027896b-758f-47c2-9fae-b6e5ac3195e5 rw rootflags=subvol=@ quiet
