// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1784029592);
user_pref("app.update.lastUpdateTime.background-update-timer", 1784072792);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1784029592);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1780384200);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.startup.homepage_override.buildID", "20260414220523");
user_pref("browser.startup.homepage_override.mstone", "140.10.0");
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.lastAppBuildId", "20260628181036");
user_pref("extensions.lastAppVersion", "9.0.5.SOURCE.f0bcd5ae1");
user_pref("extensions.lastPlatformVersion", "140.10.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.extension.hidden", false);
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.webextensions.uuids", "{\"attachmentscanner@changlab.um.edu.mo\":\"d49889e6-5183-429b-a972-5e656bdce856\",\"zoplicate@chenglongma.com\":\"06b44d44-9e26-43ef-bd99-58b92efc1854\",\"reading-list@hotmail.com\":\"01b0afb9-dbe1-4ebf-9632-4487e91fb627\",\"zoteroinspire@itp.ac.cn\":\"eb5adfb0-a2b5-4a75-a8d5-f3901238d3a1\",\"zoteroAddons@ytshen.com\":\"f85018a4-7414-4266-85ed-e02471a94328\",\"arxiv@allanchain.github.com\":\"4f86b91f-8ca1-4486-9d8e-b265348dcf79\",\"zotmeta@roadtodream.tech\":\"e7b86449-1666-4534-bd46-4f4329e8e50e\",\"delitemwithatt@redleaf.me\":\"1682987c-36ba-4561-a7b0-26306bda9108\"}");
user_pref("extensions.zotero.autoRenameFiles.done", false);
user_pref("extensions.zotero.dataDir", "/home/subhodeep/Zotero");
user_pref("extensions.zotero.downloadAssociatedFiles", false);
user_pref("extensions.zotero.duplicateLibraries", "{}");
user_pref("extensions.zotero.firstRun.skipFirefoxProfileAccessCheck", true);
user_pref("extensions.zotero.firstRun2", false);
user_pref("extensions.zotero.ignoreLegacyDataDir.auto", true);
user_pref("extensions.zotero.import.createCollection", true);
user_pref("extensions.zotero.import.fileHandling", "copy");
user_pref("extensions.zotero.inspiremeta.external_token", "FkK-DhRLRt0q9IGZyFe0zII2P5XYx9FiWaiJvQ-IVJs");
user_pref("extensions.zotero.inspiremeta.funding_pref_migrated", true);
user_pref("extensions.zotero.lastSelectedPrefPane", "zotero-prefpane-general");
user_pref("extensions.zotero.lastViewedFolder", "C262");
user_pref("extensions.zotero.lastWebDAVOrphanPurge", 1783772953);
user_pref("extensions.zotero.pane.persist", "{\"zotero-reader-sidebar-pane\":{\"collapsed\":\"true\"},\"zotero-collections-pane\":{\"width\":\"424\"},\"zotero-collections-splitter\":{\"state\":\"\"},\"zotero-layout-switcher\":{\"orient\":\"horizontal\"},\"zotero-items-splitter\":{\"state\":\"open\",\"orient\":\"horizontal\"},\"zotero-item-pane\":{\"width\":\"337\",\"height\":\"205\"},\"zotero-context-splitter\":{\"state\":\"collapsed\"},\"zotero-context-splitter-stacked\":{\"state\":\"collapsed\"},\"zotero-tags-splitter\":{\"state\":\"\"},\"zotero-tag-selector-container\":{\"height\":\"115\"}}");
user_pref("extensions.zotero.panes.abstract.open", true);
user_pref("extensions.zotero.panes.attachment-annotations.open", true);
user_pref("extensions.zotero.panes.attachment-info.open", true);
user_pref("extensions.zotero.panes.attachments.open", true);
user_pref("extensions.zotero.panes.context-all-notes.open", true);
user_pref("extensions.zotero.panes.context-item-notes.open", true);
user_pref("extensions.zotero.panes.info.open", true);
user_pref("extensions.zotero.panes.libraries-collections.open", true);
user_pref("extensions.zotero.panes.note-info.open", true);
user_pref("extensions.zotero.panes.notes.open", true);
user_pref("extensions.zotero.panes.related.open", true);
user_pref("extensions.zotero.panes.tags.open", true);
user_pref("extensions.zotero.panes.zoplicate\\@chenglongma\\.com-non-duplicates-section.open", true);
user_pref("extensions.zotero.panes.zoteroinspire\\@itp\\.ac\\.cn-zoteroinspire-references.open", true);
user_pref("extensions.zotero.postUpgradeBannerVersionShown", 9);
user_pref("extensions.zotero.prefVersion", 22);
user_pref("extensions.zotero.purge.fulltext", true);
user_pref("extensions.zotero.purge.tags", true);
user_pref("extensions.zotero.reader.darkTheme", "custom1");
user_pref("extensions.zotero.recentSaveTargets", "[{\"id\":\"C54\",\"sessionID\":\"9rLdv1iZ\"},{\"id\":\"C3\",\"sessionID\":\"MU523hpA\"}]");
user_pref("extensions.zotero.sidebarState", "{\"library\":{\"width\":240,\"open\":false},\"reader\":{\"width\":240,\"open\":false}}");
user_pref("extensions.zotero.sourceList.persist", "{\"L1\":true,\"C62\":true,\"P1\":false,\"C45\":true,\"C80\":true,\"C264\":true,\"C103\":true}");
user_pref("extensions.zotero.sync.server.username", "noir1993");
user_pref("extensions.zotero.sync.storage.protocol", "webdav");
user_pref("extensions.zotero.sync.storage.url", "app.koofr.net/dav/Koofr");
user_pref("extensions.zotero.sync.storage.username", "subhodeep.sarkar1@gmail.com");
user_pref("extensions.zotero.sync.storage.verified", true);
user_pref("extensions.zotero.tagSelector.displayAllTags", true);
user_pref("extensions.zotero.tagSelector.showAutomatic", false);
user_pref("extensions.zotero.useDataDir", true);
user_pref("extensions.zotero.zotero-reading-list.enable-keyboard-shortcuts", true);
user_pref("extensions.zotero.zotero-reading-list.label-items-when-opening-file", false);
user_pref("extensions.zotero.zotero-reading-list.label-new-items", "|none|");
user_pref("extensions.zotero.zotero-reading-list.read-status-format", 0);
user_pref("extensions.zotero.zotero-reading-list.readstatuscolumn-format-header-showicon", false);
user_pref("extensions.zotero.zotero-reading-list.status-change-on-open-item-list", "New;To Read|In Progress;In Progress");
user_pref("extensions.zotero.zotero-reading-list.statuses-and-icons-list", "New;To Read;In Progress;Read;Not Reading|⭐;📙;📖;📗;📕");
user_pref("extensions.zotero.zoteroaddons.firstInstalledVersion", "9.0.2");
user_pref("extensions.zotero.zoteroaddons.guideStatus", 1);
user_pref("extensions.zotero.zoteroaddons.tagColumnLayoutMigrated", true);
user_pref("extensions.zotero.zoteroaddonscolumns", "[{\"dataKey\":\"menu-name\",\"hidden\":false,\"ordinal\":0},{\"dataKey\":\"menu-desc\",\"hidden\":false,\"ordinal\":1},{\"dataKey\":\"menu-star\",\"hidden\":false,\"ordinal\":2,\"width\":50},{\"dataKey\":\"menu-tags\",\"hidden\":false,\"ordinal\":3,\"width\":96},{\"dataKey\":\"menu-remote-update-time\",\"hidden\":false,\"ordinal\":4,\"width\":150},{\"dataKey\":\"menu-remote-version\",\"hidden\":false,\"ordinal\":5,\"width\":100},{\"dataKey\":\"menu-local-version\",\"hidden\":false,\"ordinal\":6,\"width\":85},{\"dataKey\":\"menu-install-state\",\"hidden\":false,\"ordinal\":7,\"width\":95}]");
user_pref("extensions.zoteroOpenOfficeIntegration.lastAttemptedVersion", "9.0.0.SOURCE");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("idle.lastDailyNotification", 1784029796);
user_pref("intl.accept_languages", "en-US, en");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("privacy.purge_trackers.last_purge", "1784029796582");
user_pref("storage.vacuum.last.content-prefs.sqlite", 1780660886);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1783772680);
user_pref("zotero.addons.ui", "[\"columns\"]");
